config/routes.rb
Rails.application.routes.draw do

  resources :gossips do
  	resources :comment
  end
  resources :users
  resources :city
  root 'gossips#index'
  
  get '/team', to: 'static_pages#show_team'

  get '/contact', to: 'static_pages#show_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    # 1-N associations with user
    belongs_to :gossip
    belongs_to :user    
    # 1-N polymorphic association with comment and gossip
    belongs_to :commentable, polymorphic: true # can be associated to anything commentable
    has_many :comments, as: :commentable # is something commentable
    # 1-N associations with likes
    has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    # 1-N association with users table
    belongs_to :user
    # 1-N association with gossip_meta table
    has_many :gossip_meta
    has_many :comments
    # N-N association with tags table via the gossip_meta table
    has_many :tags, through: :gossip_meta
    # 1-N polymorphic association with comments as commentable
    has_many :comments, as: :commentable
    # 1-N associations with likes
    has_many :likes

    validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true
end

app/models/gossip_metum.rb
class GossipMetum < ApplicationRecord
    # 1-N association with gossips table
    belongs_to :gossip
    # 1-N association with tags table
    belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
    # 1-N associations with users, gossips and comments
    belongs_to :user
    # can apply to a gossip or a comment
    belongs_to :gossip, optional: true if :comment_id
    belongs_to :comment, optional: true if :gossip_id
end

app/models/message_delivering.rb
class MessageDelivering < ApplicationRecord
    # 1-N association with recipients (users) table
    # class_name tells rails recipient is a user
    belongs_to :recipient, class_name: 'User'
    # 1-N association with received_messages (private_messages) table
    # class_name tells rails received_message is a private_message
    belongs_to :received_message, class_name: 'PrivateMessage'
    end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    # 1-N association with senders (users) table
    belongs_to :sender, class_name: 'User'
    # 1-N association with message_deliverings table
    has_many :message_deliverings, foreign_key: :received_message_id
    # N-N association with recipients (users) table via message_deliverings table
    has_many :recipients, through: :message_deliverings, source: :recipient
end

app/models/tag.rb
class Tag < ApplicationRecord
    # 1-N association with gossip_meta table
    has_many :gossip_meta
    # N-N association with gossips table via gossips_meta table
    has_many :gossips, through: :gossip_meta
end

app/models/user.rb
class User < ApplicationRecord

    belongs_to :city, optional: true
    # 1-N association with gossips table
    has_many :gossips
    # 1-N association with sent_messages (private_messages) table
    # users renamed as senders for this association, class_name explains it to Rails
    has_many :sent_messages, foreign_key: :sender_id, class_name: 'PrivateMessage'
    # 1-N association with message_deliverings table
    has_many :message_deliverings, foreign_key: :recipient_id
    # N-N association with received_messages (private_messages) table via the message_deliverings table
    # renamed as recipients but doesn't show here
    has_many :received_messages, through: :message_deliverings
    # 1-N associations with comments
    has_many :comments
    # 1-N associations with likes
    has_many :likes

    #validates :password, presence: true, length: { minimum: 6 }

  	#has_secure_password
  	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  	#validates :first_name, presence: true, format: {with: /\A[a-zA-Z0-9_]{2.15}\z/, message: 'Ne dois contenir que des caractères alphanumériques ou des _'}
  	#validates :last_name, presence: true, format: {with: /\A[a-zA-Z0-9_]{2.15}\z/, message: 'Ne dois contenir que des caractères alphanumériques ou des _'}

end

app/controllers/city_controller.rb
class CityController < ApplicationController

    def show
        @city = City.find(params[:id])
        @gossips = Gossip.where(user_id:@city.users.ids)
    end
    
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController


    def new
        Comment.new
    end

    
    def show
        @comment = Comment.where(gossip_id: :gossip_id, id: params[:id])
    end
    

   def create
    puts "=" * 100
    puts params
    ûts "=" * 100
    @comment = Comment.new(content: params[:content])
   end


    def index
        @comments = Comment.where(gossip_id: :gossip_id)
    end
    
    def edit
        @comment = Comment.find(params[:id])
    end
    
    def update
        @comment = Comment.find(params[:id])
        com_params = params.require(:comment).permit(:content)
        @comment.update(com_params)
        redirect_to gossip_path
    end


    def destroy
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
    end

      
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def show
        @gossip = Gossip.find(params[:id])
        @user=User.find(@gossip.user_id)
    end

    def index 
      @gossips = Gossip.all
    end


    def new
        @gossip = Gossip.new
    end

    def edit
      @gossip = Gossip.find(params[:id])
    end

    def update
      @gossip = Gossip.find(params[:id])
      gossip_params = params.require(:gossip).permit(:title, :content)
      @gossip.update(gossip_params)
      redirect_to gossip_path
    end

    def create
        anonymous = User.new(first_name:"Anonymous", last_name:"unknown",age: 99,description: "unknown",email:"unknown#{rand(1000)}@mail.com", city_id:City.all.sample.id)
        anonymous.save
        @gossip = Gossip.new(title: params[:gossip][:title], content: params[:gossip][:content], user_id: anonymous.id)
        if @gossip.save
          redirect_to gossips_path
        else
          render 'new'
        end
    end


    def destroy
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      redirect_to gossips_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    
    def create
      user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
        @user = User.new(user_params)
        if @user.valid?
          redirect_to gossips_path
        else
          render 'new'
        end
    end

  
    def show
      @user = User.find(params[:id])
      @gossips = Gossip.where(user_id:params[:id])
    end
  

    def index
      @users=User.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/getintouch_helper.rb
module GetintouchHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/city/show.html.erb
<br></br>
<br></br>
<br></br>
<br></br>

<div class="text-center">
    <h2>Voici les Gossips qui on été écris à <%= @city.name %></h2>
    <br>
    <% @gossips.each do |gossip| %>
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 shadow-sm">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Gossip N°<%=  gossip.id%> </h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title"><%= gossip.title %><small class="text-muted"></small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>Author Name :<%=  gossip.user.first_name%></li>
                        <li>Author Last Name :<%= gossip.user.last_name%></li>
                        <li>Author age :<%= gossip.user.age %></li>
                    </ul>
                    <a href="<%= gossip_path(gossip.id) %>" <button type="button" class="btn btn-lg  btn-outline-primary">Voir plus</button></a>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/comment/edit.html.erb
<br></br>
<br></br>
<body class="text-center">
    <h2> Modifier le Commentaire</h2>
        <%= form_for @comment do |f| %>
            <div class="form-group">
                <label>Indiquez ici vos modifications</label>
                <%= f.text_area :content, class: 'form-control' %>
            </div>  
            <div class="form-group"> 
                <button type="submit" class="btn btn-success">Modifier</button>
            </div>      
        <% end %>
</body>

app/views/gossip/show_gossip.html.erb
<br></br>
<br></br>
<body class="text-center">
    <h2> Voici visionnez le Potin : <%= @thegossip.title %></h2>
    <br></br>
    <%= @thegossip.content %>
    <br></br>
    <br></br>
    Écrit par : <%= @thegossip.user.first_name %>
    <%= @thegossip.user.last_name %>
    <br></br>
    le : <%= @thegossip.created_at %>


</body>

app/views/gossips/edit.html.erb
<br></br>
<br></br>
<body class="text-center">
    <h2> Editer le Potin : <%= @gossip.title %></h2>
        <%= form_for @gossip do |f| %>
            <div class="form-group">
                <label>Titre du potin</label>
                <%= f.text_field :title, class: 'form-control' %>
            </div> 
            <div class="form-group">
                <label>Contenus</label>
                <%= f.text_area :content, class: 'form-control' %>
            </div>  
            <div class="form-group"> 
                <button type="submit" class="btn btn-primary">Modifier le Potin</button>
            </div>      
        <% end %>
</body>

app/views/gossips/index.html.erb
<br></br>
<br></br>
<br></br>
<body class="text-center">
    <main role="main" class="inner cover">
        <h1 class="cover-heading">Bienvenue <%=@user%> </h1>
        <br></br>
        <p class="lead"> Ici c'est notre super site de potins, il est chouette, non ? vous pourrez bientot crée, lire, modifier, ou encore inventer des potins sur la vie de tous les jours avec la communauté qui vous entours et ça c'est cool!</p>
    </main>
    <br></br>
    <a href="<%= new_gossip_path %>" <button type="button" class="btn btn-lg  btn-outline-success">Crée un nouveau potin!</button></a>
    <br></br>
    <h2> Voici la liste des potins déja crées! : </h2><br></br>
    
    <div class="card-deck">
    <% Gossip.all.each do |gossip| %>
            <div class="card-deck col-sm-4 mb-3 text-center">
                <div class="card mb-4 shadow-sm">
                    <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Gossip N°<%=  gossip.id%> </h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title"><%= gossip.title %><small class="text-muted"></small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                    <li>Author Name :<%=  gossip.user.first_name%></li>
                    <li>Author Last Name :<%= gossip.user.last_name%></li>
                    <li>Author age :<%= gossip.user.age %></li>
                    </ul>
                    <a href="<%= gossip_path(gossip.id) %>" <button type="button" class="btn btn-lg  btn-outline-primary">Voir plus</button></a>
                    <a href="<%= edit_gossip_path(gossip.id) %>" <button type="button" class="btn btn-lg  btn-outline-succes">Editer</button></a>
                    <a href="<%= gossip_path(gossip.id) %>" <button type="button" class="btn btn-lg  btn-outline-danger" data-confirm="Êtes vous sur de vouloir supprimer ce potin?" data-method="DELETE">Supprimer</button></a>
                </div>
            </div>
        </div>
    <% end %>
</body>

app/views/gossips/new.html.erb
<br></br>
<br></br>
<body class="text-center">
  <h2> Créer un Potin </h2>
  <%= form_for @gossip do |f| %>
    <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
      <div class="form-group">
          <label>Titre du potin</label>
          <%= f.text_field :title, class: 'form-control' %>
      </div> 
      <div class="form-group">
          <label>Contenus</label>
          <%= f.text_area :content, class: 'form-control' %>
      </div>  
      <div class="form-group"> 
          <button type="submit" class="btn btn-primary">Balancer mon Potin!</button>
      </div>      
  <% end %>
</body>

app/views/gossips/show.html.erb
<br></br>
<br></br>
<body class="text-center">
    <h2> Vous visionnez le Potin : <%= @gossip.title %></h2>
        <br></br>
            <%= @gossip.content %>
        <br></br>
        <br></br>
        <h4>Écrit par : <%= @gossip.user.first_name %>
            <%= @gossip.user.last_name %></h4>
            <h4>Provenance : <%= @gossip.user.city.name %></h4>
            <h4>le : <%= @gossip.created_at %></h4>
        <br></br>   
            <a href="<%= user_path(@gossip.user.id) %>" class="btn btn-primary">En savoir plus sur l'auteur</a>
            <a href="<%= city_path(@gossip.user.city.id) %>" class="btn btn-primary">Voir la Ville</a>
            <a href="<%= gossips_path %>" class="btn btn-primary">Revenir a l'acceuil</a>
        <br></br>
            <a href="<%= gossip_path(@gossip.id) %>" <button type="button" class="btn btn-lg  btn-outline-danger" data-confirm="Êtes vous sur de vouloir supprimer ce potin?" data-method="DELETE">Supprimer</button></a>
        <br></br>
        <h5>Checkez les Commentaires sur ce Potins !</h5>
        <div class="card-deck">
            <%=Comment.all.each do |com|%>
                <div class="card-deck col-sm-4 mb-3 text-center">
                <div class="card mb-4 shadow-sm">
                    <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Commentaire #<%=  com.id%> </h4>
                    </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>## : <%=  com.content%></li>
                        <li>Crée le : <%= com.created_at%></li>
                    </ul>
                    <a href="<%= edit_gossip_comment_path(@gossip.id,com.id) %>" <button type="button" class="btn btn-lg  btn-outline-default">Modifier ce commentaire</button></a>
                </div>
            </div>
        </div>
        <% end %>
        <h2> Ajouter un Commentaire </h2>
        <%= form_for @gossip do |f| %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <input type="hidden" name="gossip_id" value= @gossip.id >
            <div class="form-group">
                <label>Qu'as tu as dire ? </label>
                <%= f.text_field :content, class: 'form-control' %>
            </div>  
            <div class="form-group"> 
                <button type="submit" class="btn btn-primary">Envoyer mon Com'</button>
            </div>      
  <% end %>
</body>

app/views/users/new.html.erb
<br></br>
<br></br>
<h4>S'inscrire</h4>

<% if @user.errors.any? %>
    <div class="alert alert-danger">
        <ul>
            <%= @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <select>
    <%= City.all.each do |city| %>
     <option value="city"><%=city.name%></option>
        <% end %>
        </select>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.submit 'Inscription' %>
<% end %>

app/views/users/show.html.erb
<br></br>
<br></br>
<br></br>
<div class="text-center">
    Nom : <%= @user.first_name %><br>
    Prénom : <%= @user.last_name %><br>
    Age : <%= @user.age %><br>
    À propos : <%= @user.description %><br>
    Adresse e-mail : <%= @user.email %><br>
    Ville d'origine : <%= @user.city.name %><br>
    Code postal : <%= @user.city.zip_code %><br>
    <a href="<%= city_path(@user.city.id) %>" class="btn btn-primary">Plus de détails sur cette Ville</a>
</div>